### ISSUE TITLE
What's up

### ISSUE THREAD

**Issue by 5l1v3r1** [aydinnyunus/COVID-19-DETECTION#1]
...

**Comment by aydinnyunus** [comment]
It's on read me page clearly

**Comment by 5l1v3r1** [comment]
https://www.pyimagesearch.com/2020/03/16/detecting-covid-19-in-x-ray-images-with-keras-tensorflow-and-deep-learning/ 
 yeah you should share the exact link, otherwise it is obvious %70 percent of the code is the same according https://codequiry.com/. And also you should mention the tutor's name as well.

**Comment by aydinnyunus** [comment]
I add ipynb file that's real file

18 Mar 2020 Çar 01:31 tarihinde 5l1v3r1 <notifications@github.com> şunu
yazdı:
